import { DossierSchema, type Dossier } from "@/lib/domain/dossier";
import type { DomainIdentity, ResearchSnapshot } from "@/lib/domain/research";
import type { Db } from "@/lib/db/client";
import { formatIdentityBlock, sameRegistrableHost } from "@/lib/domainIdentity";
import { runAgentJson } from "@/lib/hermes/client";
import { AppError, badRequest } from "@/lib/http/errors";
import { loadDossier, loadSession, type CampaignSession } from "./sessions";

/**
 * The company dossier: generated by the brand-analyst agent from the session's
 * verified identity and research, revised from founder corrections, or edited
 * directly. Every version is checked against the identity lock before saving.
 */

const DOSSIER_TIMEOUT_MS = 240_000;

/** Identity checks the schema cannot express. Returns human-readable problems. */
export function identityProblems(dossier: Dossier, identity: DomainIdentity): string[] {
  const problems: string[] = [];
  if (!sameRegistrableHost(dossier.canonical_domain, identity.canonical_domain)) {
    problems.push(
      `canonical_domain is ${dossier.canonical_domain}, expected ${identity.canonical_domain}`,
    );
  }
  const firstParty = dossier.evidence_urls.some((url) => {
    try {
      return sameRegistrableHost(new URL(url).hostname, identity.canonical_domain);
    } catch {
      return false;
    }
  });
  if (!firstParty)
    problems.push(`evidence_urls must include a URL on ${identity.canonical_domain}`);
  return problems;
}

const STOPWORDS = new Set(
  "a an and are as at be by for from has have in into is it its of on or our that the their them they this to we with you your helps help company platform product products service services solution solutions build building built teams team".split(
    " ",
  ),
);

/** Content-word stems (first 5 letters) of a text, ignoring stopwords and short words. */
function stems(text: string): Set<string> {
  return new Set(
    (text.toLowerCase().match(/[a-z][a-z0-9-]{2,}/g) ?? [])
      .filter((w) => !STOPWORDS.has(w))
      .map((w) => w.slice(0, 5)),
  );
}

/** Minimum number of positioning terms that must also appear in the evidence. */
export const MIN_GROUNDED_TERMS = 2;

/**
 * Grounding check for agent-written dossiers: the positioning must share real
 * vocabulary with the evidence (beyond the company's own name). Catches the
 * "same name, different company" failure without hard-coding any industry.
 */
export function groundingProblems(dossier: Dossier, evidenceText: string): string[] {
  const nameStems = stems(`${dossier.company} ${dossier.canonical_domain.split(".")[0]}`);
  const evidence = stems(evidenceText);
  const claimed = [...stems(`${dossier.positioning} ${dossier.product_category ?? ""}`)].filter(
    (s) => !nameStems.has(s),
  );
  const grounded = claimed.filter((s) => evidence.has(s));
  return grounded.length >= MIN_GROUNDED_TERMS
    ? []
    : [
        `positioning is not supported by the site evidence (only ${grounded.length} matching terms)`,
      ];
}

function evidenceText(session: CampaignSession): string {
  const id = session.domain_check;
  return [id.title, id.description, id.h1, id.excerpt, session.research_snapshot.facts_markdown]
    .filter(Boolean)
    .join("\n");
}

function evidenceBlock(session: CampaignSession): string {
  const snapshot: ResearchSnapshot = session.research_snapshot;
  return [
    "=== DOMAIN IDENTITY (authoritative) ===",
    formatIdentityBlock(session.domain_check),
    "=== RESEARCH (provenance-tagged) ===",
    snapshot.facts_markdown,
    "=== END ===",
  ].join("\n");
}

async function saveDossier(db: Db, sessionId: string, dossier: Dossier): Promise<void> {
  const { error } = await db.from("brand_profiles").upsert(
    {
      session_id: sessionId,
      company: dossier.company,
      brand_voice: dossier.brand_voice,
      positioning: dossier.positioning,
      tone: dossier.tone,
      competitor_analysis: dossier.competitor_analysis,
      raw_dossier: dossier,
    },
    { onConflict: "session_id" },
  );
  if (error) throw new AppError("internal", `could not save the dossier: ${error.message}`);
}

async function runBrandAnalyst(
  session: CampaignSession,
  kind: string,
  task: string,
): Promise<Dossier> {
  const identity = session.domain_check;
  const evidence = evidenceText(session);
  // Identity and grounding failures are schema issues, so the agent gets one chance to correct them.
  const schema = DossierSchema.superRefine((dossier, ctx) => {
    for (const message of [
      ...identityProblems(dossier, identity),
      ...groundingProblems(dossier, evidence),
    ]) {
      ctx.addIssue({ code: "custom", message });
    }
  });
  const { data } = await runAgentJson({
    agent: "brand-analyst",
    kind,
    kamiSessionId: session.id,
    timeoutMs: DOSSIER_TIMEOUT_MS,
    schema,
    input: `${task}\n\n${evidenceBlock(session)}`,
  });
  return {
    ...data,
    canonical_domain: identity.canonical_domain,
    identity_confidence: identity.confidence,
  };
}

export async function generateDossier(db: Db, sessionId: string): Promise<Dossier> {
  const session = await loadSession(db, sessionId);
  const goals = session.goals.length ? `Founder goals: ${session.goals.join(", ")}.` : "";
  const stage = session.stage ? `Stage: ${session.stage}.` : "";
  const dossier = await runBrandAnalyst(
    session,
    "dossier_generate",
    `Compile the dossier for ${session.canonical_domain}. ${goals} ${stage}`.trim(),
  );
  await saveDossier(db, sessionId, dossier);
  await db
    .from("agent_sessions")
    .update({ status: "dossier_ready", dossier_confirmed_at: null })
    .eq("id", sessionId);
  return dossier;
}

export async function reviseDossier(
  db: Db,
  sessionId: string,
  correction: string,
): Promise<Dossier> {
  const session = await loadSession(db, sessionId);
  const current = await loadDossier(db, sessionId);
  if (!current) throw badRequest("generate the dossier before revising it");
  const dossier = await runBrandAnalyst(
    session,
    "dossier_revise",
    [
      `Revise the dossier for ${session.canonical_domain} using the founder's correction.`,
      `Founder correction:\n"""\n${correction}\n"""`,
      `Current dossier:\n\`\`\`json\n${JSON.stringify(current, null, 2)}\n\`\`\``,
    ].join("\n\n"),
  );
  await saveDossier(db, sessionId, dossier);
  await db.from("agent_sessions").update({ dossier_confirmed_at: null }).eq("id", sessionId);
  return dossier;
}

/** Save the founder's direct edits. */
export async function updateDossier(db: Db, sessionId: string, edited: unknown): Promise<Dossier> {
  const session = await loadSession(db, sessionId);
  const dossier = DossierSchema.parse({
    ...(edited as object),
    canonical_domain: session.canonical_domain,
  });
  const problems = identityProblems(dossier, session.domain_check);
  if (problems.length) throw badRequest(problems.join("; "));
  await saveDossier(db, sessionId, dossier);
  // The founder confirms the dossier as it stands; any change needs a fresh "That's us".
  await db.from("agent_sessions").update({ dossier_confirmed_at: null }).eq("id", sessionId);
  return dossier;
}
